### ISSUE TITLE
Code/Server/Server.py get_interface_ip() fails on RasPi 4 with Raspberry Pi OS Bookworm

### ISSUE THREAD

**Issue by emendir** [Freenove/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi#30]
When running the server code with the following commands
```sh
cd ~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
sudo python main.py
```

I get the following error:

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 85, in <module>
    myshow=MyWindow()
           ^^^^^^^^^^
  File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 23, in __init__
    self.on_and_off_server()
  File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 50, in on_and_off_server
    self.server.turn_on_server()
  File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 50, in turn_on_server
    HOST=self.get_interface_ip()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 44, in get_interface_ip
    return socket.inet_ntoa(fcntl.ioctl(s.fileno(),
                            ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 99] Cannot assign requested address
```

OS info:
`Linux raspberrypi 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux`

The system has an IP network connection while producing this error.

Any ideas as to the cause of and solution to this problem?

**Comment by Shaynee-MO** [comment]
The system has an IP network connection while producing this error.
Would you mind sending us a screenshot of the IP network connection?

**Comment by emendir** [comment]
I'm using the raspberry pi's ethernet port. (`eth0`)
Here's the network connection config as displayed by the `ip addr` command, with sensitive digits blanked out with `X`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
    inet 192.168.XX.XX/24 brd 192.168.XX.255 scope global dynamic noprefixroute eth0
       valid_lft 259098sec preferred_lft 259098sec
    inet6 fe80::XXXX:XXXX:XXXX:XXXX/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
   link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
```

**Comment by Shaynee-MO** [comment]
Here is an image of our raspberry pi OS, you can download and write it to your Raspberry Pi and try again.
https://drive.google.com/file/d/1wbHLgsfKt4HgR8Ck9yGjvVc2Tvtvsyqj/view?usp=drive_link

**Comment by emendir** [comment]
I have managed to narrow down the issue a little further. This error only occurs when using wired-LAN using the RasPi's ethernet port instead of wireless LAN.

## Workaround:
Connect to wireless LAN instead of wired-LAN.

Having found this workaround, the problem is still not solved.

I expect we can call it a software bug, that using wired-LAN causes this error?  
Or is this a limitation of the network architecture between client and server?

In the latter case, it would be useful to provide the user with a helpful message instructing them to connect to a wireless LAN instead of this relatively useless error-message.

**Comment by Shaynee-MO** [comment]
Hi! Many thanks for the input. We will make it clear in our tutorial. We are sorry for any inconvenience it may cause.

**Comment by developervova** [comment]
Hi! Where can I see this explanation?

**Comment by jaywalker68** [comment]
Hi, I'm having the same issue when I run sudo python camera.py. I'm using a raspberry pi 5, connected to it via wifi and using RealVNC on Windows 11. When I run env | grep XDG I see  XDG_RUNTIME_DIR=/run/user/1000.

**Comment by techapplez** [comment]
> When running the server code with the following commands
> 
> ```shell
> cd ~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
> sudo python main.py
> ```
> 
> I get the following error:
> 
> ```
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> Traceback (most recent call last):
>   File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 85, in <module>
>     myshow=MyWindow()
>            ^^^^^^^^^^
>   File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 23, in __init__
>     self.on_and_off_server()
>   File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/main.py", line 50, in on_and_off_server
>     self.server.turn_on_server()
>   File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 50, in turn_on_server
>     HOST=self.get_interface_ip()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hex/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Server.py", line 44, in get_interface_ip
>     return socket.inet_ntoa(fcntl.ioctl(s.fileno(),
>                             ^^^^^^^^^^^^^^^^^^^^^^^
> OSError: [Errno 99] Cannot assign requested address
> ```
> 
> OS info: `Linux raspberrypi 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux`
> 
> The system has an IP network connection while producing this error.
> 
> Any ideas as to the cause of and solution to this problem?

I think i had the same error and you only have to run: 

`cd ~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
sudo python main.py -tn`

this works if you use ssh and no vnc.
