### ISSUE TITLE
Error 5

### ISSUE THREAD

**Issue by Jomaka37** [Freenove/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi#33]
Hi I have assembled my Robotter BI page 67 and executed all the codes correctly. But when I want to test the servos now, it just says "Input/Output Error (Error 5). if I want to query the battery status or the ultrasonic sensor, the same thing happens. What can I do? Thanks in advance

**Comment by Shaynee-MO** [comment]
Please run the following commands one by one and send us screenshots of the results. Many thanks.
getconf LONG_BIT
cat /proc/cpuinfo
cat /etc/rpi-issue

**Comment by mickRayner** [comment]
I have the same issue as above results as sequested are below
hexabot@raspberrypi:~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server $ getconf LONG_BIT
64

cat /proc/cpuinfo
cat /etc/rpi-issue
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Revision	: c03115
Serial		: 10000000817f3c71
Model		: Raspberry Pi 4 Model B Rev 1.5
Raspberry Pi reference 2024-07-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 48efb5fc5485fafdc9de8ad481eb5c09e1182656, stage4

**Comment by Shaynee-MO** [comment]
Please check the following:
1. Whether the connector is contacted well.
![image](https://github.com/user-attachments/assets/624bac7a-a6ff-49cc-9e54-893a1517a2c6)
2. Whether both two power switches on the robot board are ON.
3. Whether I2C is enabled.
4. Please run i2cdetect -y 1 and send us a screenshot of the results.
![image](https://github.com/user-attachments/assets/8433dbc5-8dc8-4e82-a34c-0c4375663131)

**Comment by mickRayner** [comment]
Hi
We checked the connector as described and it's fine.  We have seen that one
side of our power supply continues to drop out or just not come on.  We
found one of the connectors was loose and wouldn't go into the socket all
the way.  On closer inspection it seems this might be the issue.  I am sure
bad power would hurt us. We swapped the battery holder cables over to
ensure it was not the connector on the board. The connector on the right in
the photo works consistently the one on the left does not. (photo attached)

i2cdetect -y 1 results

***@***.***:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 41 -- -- -- -- -- -- 48 -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --
***@***.***:~ $


results from other tests below

*On attempt to move head via Client app*


***@***.***:~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
$ sudo python3 main.py -t -n

Open TCP

Server address: 192.168.5.60

socket video connected ...

[0:17:16.202288395] [1983]  INFO Camera camera_manager.cpp:316 libcamera
v0.3.1+50-69a894c4

[0:17:16.228122349] [1985]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning
- please consider moving SDN inside rpi.denoise

[0:17:16.230254480] [1985]  INFO RPI vc4.cpp:447 Registered camera
***@***.******@***.*** to Unicam device /dev/media2 and ISP
device /dev/media1

[0:17:16.230358275] [1985]  INFO RPI pipeline_base.cpp:1125 Using
configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'

Client connection successful !

[0:17:16.252476260] [1983]  INFO Camera camera.cpp:1191 configuring
streams: (0) 400x300-XBGR8888 (1) 640x480-SGBRG10_CSI2P

[0:17:16.252932442] [1985]  INFO RPI vc4.cpp:622 Sensor:
***@***.******@***.*** - Selected sensor format:
640x480-SGBRG10_1X10 - Selected unicam format: 640x480-pGAA

['CMD_POWER', '']

['CMD_POWER', '']

['CMD_HEAD#1#139', '']

Exception in thread Thread-3 (receive_instruction):

Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.11/threading.py", line 975, in run

    self._target(*self._args, **self._kwargs)

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Server.py",
line 179, in receive_instruction

    self.servo.setServoAngle(int(data[1]),int(data[2]))

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Servo.py",
line 22, in setServoAngle

    self.pwm_41.setPWM(channel, 0, int(date))

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py",
line 63, in setPWM

    self.write(self.__LED0_ON_H+4*channel, on >> 8)

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py",
line 36, in write

    self.bus.write_byte_data(self.address, reg, value)

OSError: [Errno 5] Input/output error



Connection lost and remote terminal (SSH) needed to be reconnected



*sudo python test.py Buzzer - pass*

*sudo python test.py Led - pass*

*sudo python test.py Ultrasonic - pass*

*sudo python test.py ADC - fail*

***@***.***:~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
$ sudo python test.py ADC

Program is starting ...

Traceback (most recent call last):

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/test.py",
line 145, in <module>

    test_Adc()

    ^^^^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/test.py",
line 85, in test_Adc

    Power=adc.batteryPower()

          ^^^^^^^^^^^^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/ADC.py",
line 25, in batteryPower

    val0 = self.batteryValue(0)

           ^^^^^^^^^^^^^^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/ADC.py",
line 21, in batteryValue

    return self.adc.analogRead(chn)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/ADCDevice.py",
line 52, in analogRead

    value = self.bus.read_byte_data(self.address, self.cmd|(((chn<<2 |
chn>>1)&0x07)<<4))


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: [Errno 5] Input/output error


*sudo python test.py Servo - fail*

***@***.***:~/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server
$ sudo python test.py Servo

Traceback (most recent call last):

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/test.py",
line 47, in <module>

    servo=Servo()

          ^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Servo.py",
line 11, in __init__

    self.pwm_41 = PCA9685(0x41, debug=True)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py",
line 32, in __init__

    self.write(self.__MODE1, 0x00)

  File
"/home/hexabot/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py",
line 36, in write

    self.bus.write_byte_data(self.address, reg, value)

OSError: [Errno 5] Input/output error


Thanks
Mick Rayner

**Comment by Shaynee-MO** [comment]
We will send you a new battery holder.
Please send your info for shipping to support@freenove.com.
*Name:
*Address1:
Address2:
*City:
*Region:
*Post Code:
*Country:
Phone Number:

**Comment by mickRayner** [comment]
Thanks Shaynee
