### ISSUE TITLE
i2cdetect -y 1 with nothing. is it normal ?

### ISSUE THREAD

**Issue by Sam-saidane** [Freenove/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi#9]
Hi,
 i can't do any test.py or main.py... i hava an error "OSError: [Errno 121] Remote I/O error" all the time.
can you help me ?

log:
i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by Sam-saidane** [comment]
start .. 

No correct I2C address found, 
Please use command 'i2cdetect -y 1' to check the I2C address! 
Program Exit. 



 I2C is enable

**Comment by bravok** [comment]
Having the same issue getting the servos calibrated and installed.
It worked once last night, but this morning I'm getting the following
` sudo python Servo.py
Now servos will rotate to certain angles.
Please keep the program running when installing the servos.
After that, you can press ctrl-C to end the program.
Traceback (most recent call last):
  File "/home/kris/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Servo.py", line 51, in <module>
    servo_installation_position()
  File "/home/kris/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Servo.py", line 35, in servo_installation_position
    S=Servo()     
  File "/home/kris/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/Servo.py", line 10, in __init__
    self.pwm_40 = PCA9685(0x40, debug=True)
  File "/home/kris/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py", line 32, in __init__
    self.write(self.__MODE1, 0x00)
  File "/home/kris/Freenove_Big_Hexapod_Robot_Kit_for_Raspberry_Pi/Code/Server/PCA9685.py", line 36, in write
    self.bus.write_byte_data(self.address, reg, value)
OSError: [Errno 121] Remote I/O error`

 i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by bravok** [comment]
Okay solved for me: The connector between the servo controller board and the raspberry pi wasn't completely seated. I pushed it down as far as it would go, reran the program and it works.

**Comment by bravok** [comment]
@Sam-saidane do you still have this issue?

**Comment by Shaynee-MO** [comment]
@Sam-saidane Please unplug and replug the connector and check again.
If the issue remains, please send an email to support@freenove.com. 
![image](https://user-images.githubusercontent.com/118493923/211448886-0f0e5bf8-f5f6-4329-af36-6be100882779.png)
![image](https://user-images.githubusercontent.com/118493923/211448926-e089a6e0-107f-46c8-bf70-838bc6388067.png)
